site_name: Guia de Faturamento
theme: 
  name: material
  logo: assets/logo-branca.png
  language: pt-BR
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.instant
    - navigation.sections
    - navigation.path
    - navigation.top
    - toc.follow
    - search.suggest
    - content.tabs.link
    - navigation.footer
copyright: Todos os direitos reservados &copy; 2024 Global Alumínios</br>A reprodução e compartilhamento do conteúdo desse site fora dos canais da empresa é expressamente proibida

nav:
    - Emissão de Nota Fiscal:
        - index.md
        - Processo de emissão: emissao.md
        - Processo de impressão: impressao.md
    - Glossário:
       # - index.md
        - O que é canal de origem?: glossario/o-que-e-canal-de-origem.md

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format


plugins:
  - search
